using Microsoft.OpenApi.Models;
using Library.Infrastructure;
using Library.Application;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Inject Infrastructure
builder.Services.AddInfrastuctureService(builder.Configuration);

// Inject Application
builder.Services.AddApplicationService();

// Add Controllers
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Library API",
        Version = "v1"
    });

    // Locate the XML file being generated by ASP.NET Core
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);  // Include the XML comments in Swagger
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors(x => x.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin());
app.MapControllers();

app.Run();